name: run tests

on:
  push:
    branches:
      - main
      - staging
      - trying

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v -covermode=count

  ready:
    name: ready
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - run: echo "success!"
